<a href="https://colab.research.google.com/github/AliKhanSajjad/DS_ML_Training_Excercises/blob/master/Excercise1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

My excercises on Numpy, Pandas, Matplot and many more..

In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt

In [ ]:
rnd = np.random.rand(3,5)

In [ ]:
df = pd.DataFrame(rnd)

In [ ]:
df 

0         1         2         3         4
0  0.516399  0.570668  0.028474  0.171522  0.685277
1  0.833897  0.306966  0.893613  0.721544  0.189939
2  0.554228  0.352132  0.181892  0.785602  0.965483

In [ ]:
df[0]

0    0.516399
1    0.833897
2    0.554228
Name: 0, dtype: float64

In [ ]:
np.random.seed()

In [ ]:
arr = np.arange(1,10).reshape(3,3)

In [ ]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
np.shape(arr)

(3, 3)

In [ ]:
pd.Series([1,2,3,5,6,7],index=['a','b','c','d','e','f'])

a    1
b    2
c    3
d    5
e    6
f    7
dtype: int64

In [ ]:
data = {'Name':['Tom', 'Jack', 'Steve', 'Ricky'],'Age':[28,34,29,42]}
df = pd.DataFrame(data,index=['a','b','c','d'])

In [ ]:
df

Name  Age
a    Tom   28
b   Jack   34
c  Steve   29
d  Ricky   42

In [ ]:
df['Salary']=[5000,6000,7000,8000]

In [ ]:
df.drop(labels='Salary',axis=1)

Name  Age
a    Tom   28
b   Jack   34
c  Steve   29
d  Ricky   42

In [ ]:
df

Name  Age  Salary
a    Tom   28    5000
b   Jack   34    6000
c  Steve   29    7000
d  Ricky   42    8000

In [ ]:
df[df['Salary']>6000]

Name  Age  Salary
c  Steve   29    7000
d  Ricky   42    8000

In [ ]:
df.tail(2)

Name  Age  Salary
c  Steve   29    7000
d  Ricky   42    8000

In [ ]:
df1 = df.append({'Name':'Sajjad','Age':38,'Salary':7000},ignore_index=True,verify_integrity=True)

In [ ]:
df1

Name  Age  Salary
0     Tom   28    5000
1    Jack   34    6000
2   Steve   29    7000
3   Ricky   42    8000
4  Sajjad   38    7000

In [ ]:
df1.describe()

Age       Salary
count   5.000000     5.000000
mean   34.200000  6600.000000
std     5.932959  1140.175425
min    28.000000  5000.000000
25%    29.000000  6000.000000
50%    34.000000  7000.000000
75%    38.000000  7000.000000
max    42.000000  8000.000000

In [ ]:
df1.sort_values('Salary')

Name  Age  Salary
0     Tom   28    5000
1    Jack   34    6000
2   Steve   29    7000
4  Sajjad   38    7000
3   Ricky   42    8000

In [ ]:
df1.groupby('Salary')

In [ ]:
df1

Name  Age  Salary
0     Tom   28    5000
1    Jack   34    6000
2   Steve   29    7000
3   Ricky   42    8000
4  Sajjad   38    7000

In [ ]:
item = [n*2 for n in range(10)]

In [ ]:
print(item)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [ ]:
import random
random.random()

0.04930530050363591

In [ ]:
items = [10, 4, 5, 2, 1]
random.shuffle(items)

In [ ]:
items.sort()

In [ ]:
print(items)

[10, 5, 4, 2, 1, 5, 6]


In [ ]:
items.remove(5)

In [ ]:
print(items)

[10, 4, 2, 1, 5, 6]


In [ ]:
str1 = "I am sajjad ali khan"

In [ ]:
str1.split()

['I', 'am', 'sajjad', 'ali', 'khan']

In [ ]:
list()

['I',
 ' ',
 'a',
 'm',
 ' ',
 's',
 'a',
 'j',
 'j',
 'a',
 'd',
 ' ',
 'a',
 'l',
 'i',
 ' ',
 'k',
 'h',
 'a',
 'n']

In [ ]:
tup = ('sajjad','ali','khan','ali')

In [ ]:
tup[2]

'khan'

In [ ]:
st = {'sajjad','ali','khan','ali'}

In [ ]:
st

{'ali', 'khan', 'sajjad'}

In [ ]:
tup

('sajjad', 'ali', 'khan', 'ali')

In [ ]:
set(tup)

{'ali', 'khan', 'sajjad'}

In [ ]:
set.union(st)

{'ali', 'khan', 'sajjad'}

In [ ]:
ad = dict({'a':10,'b':20})

In [ ]:
ad.items()

dict_items([('a', 10), ('b', 20)])

In [ ]:
m = dict([('a', 10), ('b', 20)])

In [ ]:
m.

{'a': 10, 'b': 20}

In [ ]:
duplicates = ['a','b','c','d','d','d','e','a','b','f','g','g','h']
uniqueItems = list(set(duplicates))

In [ ]:
print(sorted(uniqueItems))

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']


In [ ]:
uniqueItems.sort()

In [ ]:
uniqueItems

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']

In [ ]:
wordList='1,3,2,4,5,3,2,1,4,3,2'.split(',')

In [ ]:
wordList

['1', '3', '2', '4', '5', '3', '2', '1', '4', '3', '2']